// src/lib/components/Companies.svelte
<script lang="ts">
	import Image from '@datocms/svelte/components/Image/Image.svelte';
	import ExternalLink from './ExternalLink.svelte';
	import type { Company } from '$lib/types.js';

	let { companies, title }: { companies: Company[]; title: string } = $props();
</script>

<section class="companies">
	<h2>{title}</h2>
	{#each companies as company, index (company.id)}
		<div id={company.tag} class="company {index % 2 === 0 ? 'image-left' : 'image-right'}">
			<Image data={company.image.responsiveImage} class="company-image" />
			<div class="description">
				<h3>{company.title}</h3>
				<div class="container">
					{@html company.description}
				</div>
				{#if company.dualLinkGroup}
					<div class="dual-links">
						<div class="dual-link">
							<h4>{company.dualLinkGroup.title1}</h4>
							{#each company.dualLinkGroup.linkGroups1 as group (group.id)}
								<h5>{group.title}</h5>
								<div class="links">
									{#each group.links as link (link.id)}
										<ExternalLink text={link.text} href={link.link} />
									{/each}
								</div>
							{/each}
						</div>
						<div class="dual-link">
							<h4>{company.dualLinkGroup.title2}</h4>
							{#each company.dualLinkGroup.linkGroups2 as group (group.id)}
								<h5>{group.title}</h5>
								<div class="links">
									{#each group.links as link (link.id)}
										<ExternalLink text={link.text} href={link.link} />
									{/each}
								</div>
							{/each}
						</div>
					</div>
				{:else}
					<div class="links">
						{#each company.links as link (link.id)}
							<ExternalLink text={link.text} href={link.link} />
						{/each}
					</div>
				{/if}
			</div>
		</div>
	{/each}
</section>

<style>
	.companies {
		margin-top: calc(15 / 375 * 100vw);
		padding: calc(20 / 375 * 100vw) calc(20 / 375 * 100vw) calc(40 / 375 * 100vw);

		h2 {
			font-weight: 500;
			font-size: calc(18 / 375 * 100vw);
			line-height: calc(20 / 375 * 100vw);
			letter-spacing: 0.02em;
			text-transform: uppercase;
			color: #141212;
		}

		.company {
			display: grid;
			grid-template-columns: 100%;

			:global(.company-image) {
				width: 100%;
				object-fit: cover;
			}

			.description {
				width: 100%;
				margin-top: calc(20 / 375 * 100vw);

				h3 {
					font-weight: 500;
					font-size: calc(28 / 375 * 100vw);
					line-height: calc(32 / 375 * 100vw);
					letter-spacing: 0.02em;
				}

				.container {
					margin-top: calc(15 / 375 * 100vw);
				}
			}

			.description :global {
				p {
					font-size: calc(18 / 375 * 100vw);
					line-height: calc(22 / 375 * 100vw);
					letter-spacing: 0.02em;
				}

				small {
					font-size: calc(14 / 375 * 100vw);
					line-height: calc(16 / 375 * 100vw);
				}

				p + p {
					margin-top: calc(15 / 375 * 100vw);
				}
			}

			.description .links {
				margin-top: calc(20 / 375 * 100vw);

				:global(div + div) {
					margin-top: calc(12 / 375 * 100vw);
				}
			}

			.description .dual-links {
				margin-top: calc(30 / 375 * 100vw);

				h4,
				h5 {
					font-weight: 500;
					letter-spacing: 0.02em;
					text-transform: uppercase;
				}

				h4 {
					font-size: calc(20 / 375 * 100vw);
					line-height: calc(24 / 375 * 100vw);
				}

				.links {
					margin-top: calc(15 / 375 * 100vw);
				}

				h5 {
					margin-top: calc(20 / 375 * 100vw);
					font-size: calc(16 / 375 * 100vw);
					line-height: calc(18 / 375 * 100vw);
				}

				.dual-link + .dual-link {
					margin-top: calc(30 / 375 * 100vw);
				}
			}

			&.image-left {
				:global(.company-image) {
					order: 1;
				}

				.description {
					order: 2;
				}
			}

			&.image-right {
				:global(.company-image) {
					order: 1;
				}

				.description {
					order: 1;
				}
			}
		}

		.company:first-of-type {
			margin-top: calc(30 / 375 * 100vw);
		}

		.company + .company {
			margin-top: calc(50 / 375 * 100vw);
		}

		@media (min-width: 768px) {
			margin-top: calc(126 / 1440 * 100vw);
			padding: calc(40 / 1440 * 100vw) calc(40 / 1440 * 100vw) calc(150 / 1440 * 100vw);

			h2 {
				font-size: calc(24 / 1440 * 100vw);
				line-height: calc(26 / 1440 * 100vw);
			}

			.company {
				grid-template-columns: 1fr 1fr;
				align-items: center;

				:global(.company-image) {
					min-height: 100%;
					height: calc(650 / 1440 * 100vw);
				}

				.description {
					max-width: calc(600 / 1440 * 100vw);
					margin-top: 0;

					h3 {
						font-size: calc(64 / 1440 * 100vw);
						line-height: calc(70 / 1440 * 100vw);
					}

					.container {
						margin-top: calc(60 / 1440 * 100vw);
					}
				}

				.description :global {
					p {
						font-size: calc(24 / 1440 * 100vw);
						line-height: calc(27 / 1440 * 100vw);
					}

					small {
						font-size: calc(16 / 1440 * 100vw);
						line-height: calc(18 / 1440 * 100vw);
					}

					p + p {
						margin-top: calc(20 / 1440 * 100vw);
					}
				}

				.description .links {
					margin-top: calc(40 / 1440 * 100vw);

					:global(div + div) {
						margin-top: calc(15 / 1440 * 100vw);
					}
				}

				.description .dual-links {
					margin-top: calc(60 / 1440 * 100vw);
					display: flex;
					justify-content: space-between;
					align-items: flex-start;
					flex-direction: row;

					h4 {
						font-size: calc(24 / 1440 * 100vw);
						line-height: calc(27 / 1440 * 100vw);
					}

					.links {
						margin-top: calc(25 / 1440 * 100vw);
					}

					h5 {
						margin-top: calc(30 / 1440 * 100vw);
						font-size: calc(22 / 1440 * 100vw);
						line-height: calc(24 / 1440 * 100vw);
						width: min-content;
					}

					.dual-link + .dual-link {
						margin-top: 0;
					}
				}

				&.image-left {
					:global(.company-image) {
						order: 1;
					}

					.description {
						order: 2;
						padding-left: calc(135 / 1440 * 100vw);
					}
				}

				&.image-right {
					:global(.company-image) {
						order: 2;
					}

					.description {
						order: 1;
						padding-right: calc(135 / 1440 * 100vw);
					}
				}
			}

			.company:first-of-type {
				margin-top: calc(50 / 1440 * 100vw);
			}

			.company + .company {
				margin-top: calc(150 / 1440 * 100vw);
			}
		}
	}
</style>

// components/Companies.vue
<template>
  <section class="companies">
    <h2>{{ title }}</h2>
    <div
      v-for="(company, index) in companies"
      :key="company.id"
      :id="company.tag"
      class="company"
      :class="index % 2 === 0 ? 'image-left' : 'image-right'"
    >
      <datocms-image
        :data="company.image.responsiveImage"
        class="company-image"
      />
      <div class="description">
        <h3>{{ company.title }}</h3>
        <div v-html="company.description" class="container" />
        <div v-if="company.dualLinkGroup" class="dual-links">
          <div class="dual-link">
            <h4>{{ company.dualLinkGroup.title1 }}</h4>
            <template v-for="group in company.dualLinkGroup.linkGroups1">
              <h5 :key="group.id">{{ group.title }}</h5>
              <div class="links" :key="group.id">
                <Link
                  v-for="link in group.links"
                  :key="link.id"
                  :text="link.text"
                  :href="link.link"
                  class="link-wrapper"
                />
              </div>
            </template>
          </div>
          <div class="dual-link">
            <h4>{{ company.dualLinkGroup.title2 }}</h4>
            <template v-for="group in company.dualLinkGroup.linkGroups2">
              <h5 :key="group.id">{{ group.title }}</h5>
              <div class="links" :key="group.id">
                <Link
                  :text="link.text"
                  :href="link.link"
                  class="link-wrapper"
                  v-for="link in group.links"
                  :key="link.id"
                />
              </div>
            </template>
          </div>
        </div>
        <div class="links" v-else>
          <Link
            v-for="link in company.links"
            :key="link.id"
            :text="link.text"
            :href="link.link"
            class="link-wrapper"
          />
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { Image } from 'vue-datocms'

export default {
  components: {
    'datocms-image': Image,
  },
  props: {
    companies: {
      type: Array,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
  },
}
</script>

<style lang="scss">
.companies {
  margin-top: vwS(15);
  padding: vwS(20) vwS(20) vwS(40);

  h2 {
    font-weight: 500;
    font-size: vwS(18);
    line-height: vwS(20);
    letter-spacing: 0.02em;
    text-transform: uppercase;
    color: #141212;
  }

  .company {
    display: grid;
    grid-template-columns: 100%;

    .company-image {
      width: 100%;
      object-fit: cover;
    }

    .description {
      width: 100%;
      margin-top: vwS(20);

      h3 {
        font-weight: 500;
        font-size: vwS(28);
        line-height: vwS(32);
        letter-spacing: 0.02em;
      }

      .container {
        margin-top: vwS(15);
      }

      p {
        font-size: vwS(18);
        line-height: vwS(22);
        letter-spacing: 0.02em;

        small {
          font-size: vwS(14);
          line-height: vwS(16);
        }
      }

      p + p {
        margin-top: vwS(15);
      }

      .links {
        margin-top: vwS(20);

        .link-wrapper + .link-wrapper {
          margin-top: vwS(12);
        }
      }

      .dual-links {
        margin-top: vwS(30);

        h4,
        h5 {
          font-weight: 500;
          letter-spacing: 0.02em;
          text-transform: uppercase;
        }

        h4 {
          font-size: vwS(20);
          line-height: vwS(24);
        }

        .links {
          margin-top: vwS(15);
        }

        h5 {
          margin-top: vwS(20);
          font-size: vwS(16);
          line-height: vwS(18);
        }

        .dual-link + .dual-link {
          margin-top: vwS(30);
        }
      }
    }

    &.image-left {
      .company-image {
        order: 1;
      }

      .description {
        order: 2;
      }
    }

    &.image-right {
      .company-image {
        order: 1;
      }

      .description {
        order: 1;
      }
    }
  }

  .company:first-of-type {
    margin-top: vwS(30);
  }

  .company + .company {
    margin-top: vwS(50);
  }

  @include above(small) {
    margin-top: vw(126);
    padding: vw(40) vw(40) vw(150);

    h2 {
      font-size: vw(24);
      line-height: vw(26);
    }

    .company {
      grid-template-columns: 1fr 1fr;
      align-items: center;

      .company-image {
        min-height: 100%;
        height: vw(650);
      }

      .description {
        max-width: vw(600);
        margin-top: 0;

        h3 {
          font-size: vw(64);
          line-height: vw(70);
        }

        .container {
          margin-top: vw(60);
        }

        p {
          font-size: vw(24);
          line-height: vw(27);

          small {
            font-size: vw(16);
            line-height: vw(18);
          }
        }

        p + p {
          margin-top: vw(20);
        }

        .links {
          margin-top: vw(40);

          .link-wrapper + .link-wrapper {
            margin-top: vw(15);
          }
        }

        .dual-links {
          margin-top: vw(60);
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          flex-direction: row;

          h4 {
            font-size: vw(24);
            line-height: vw(27);
          }

          .links {
            margin-top: vw(25);
          }

          h5 {
            margin-top: vw(30);
            font-size: vw(22);
            line-height: vw(24);
            width: min-content;
          }

          .dual-link + .dual-link {
            margin-top: 0;
          }
        }
      }

      &.image-left {
        .company-image {
          order: 1;
        }

        .description {
          order: 2;
          padding-left: vw(135);
        }
      }

      &.image-right {
        .company-image {
          order: 2;
        }

        .description {
          order: 1;
          padding-right: vw(135);
        }
      }
    }

    .company:first-of-type {
      margin-top: vw(50);
    }

    .company + .company {
      margin-top: vw(150);
    }
  }
}
</style>
