// components/Footer.vue
<template>
  <footer>
    <h2>ASCENDO</h2>
    <div class="information">
      <div class="section">
        <h3>Información de Contacto</h3>
        <address class="details">
          <ul>
            <li class="footer-link">
              <svg
                class="phone-svg"
                viewBox="0 0 22 22"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M20.8881 15.9201V18.9201C20.8892 19.1986 20.8322 19.4743 20.7206 19.7294C20.6091 19.9846 20.4454 20.2137 20.2402 20.402C20.035 20.5902 19.7927 20.7336 19.5289 20.8228C19.265 20.912 18.9855 20.9452 18.7081 20.9201C15.631 20.5857 12.6751 19.5342 10.0781 17.8501C7.66194 16.3148 5.61345 14.2663 4.07812 11.8501C2.38809 9.2413 1.33636 6.27109 1.00812 3.1801C0.983127 2.90356 1.01599 2.62486 1.10462 2.36172C1.19324 2.09859 1.33569 1.85679 1.52288 1.65172C1.71008 1.44665 1.93792 1.28281 2.19191 1.17062C2.44589 1.05843 2.72046 1.00036 2.99812 1.0001H5.99812C6.48342 0.995321 6.95391 1.16718 7.32188 1.48363C7.68985 1.80008 7.93019 2.23954 7.99812 2.7201C8.12474 3.68016 8.35957 4.62282 8.69812 5.5301C8.83266 5.88802 8.86178 6.27701 8.78202 6.65098C8.70227 7.02494 8.51698 7.36821 8.24812 7.6401L6.97812 8.9101C8.40167 11.4136 10.4746 13.4865 12.9781 14.9101L14.2481 13.6401C14.52 13.3712 14.8633 13.1859 15.2372 13.1062C15.6112 13.0264 16.0002 13.0556 16.3581 13.1901C17.2654 13.5286 18.2081 13.7635 19.1681 13.8901C19.6539 13.9586 20.0975 14.2033 20.4146 14.5776C20.7318 14.9519 20.9003 15.4297 20.8881 15.9201Z"
                  stroke="#141212"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <a href="tel:+18095656687">+1 (809) 565-6687</a>
            </li>
            <li class="footer-link">
              <svg
                class="whatsapp-svg"
                viewBox="0 0 20 20"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M19 9.50003C19.0034 10.8199 18.6951 12.1219 18.1 13.3C17.3944 14.7118 16.3098 15.8992 14.9674 16.7293C13.6251 17.5594 12.0782 17.9994 10.5 18C9.18013 18.0035 7.87812 17.6951 6.7 17.1L1 19L2.9 13.3C2.30493 12.1219 1.99656 10.8199 2 9.50003C2.00061 7.92179 2.44061 6.37488 3.27072 5.03258C4.10083 3.69028 5.28825 2.6056 6.7 1.90003C7.87812 1.30496 9.18013 0.996587 10.5 1.00003H11C13.0843 1.11502 15.053 1.99479 16.5291 3.47089C18.0052 4.94699 18.885 6.91568 19 9.00003V9.50003Z"
                  stroke="#141212"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <a href="tel:+18297152501">+1 (829) 715-2501</a>
            </li>
            <li class="footer-link">
              <svg
                class="email-svg"
                viewBox="0 0 22 18"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M3 1H19C20.1 1 21 1.9 21 3V15C21 16.1 20.1 17 19 17H3C1.9 17 1 16.1 1 15V3C1 1.9 1.9 1 3 1Z"
                  stroke="#141212"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
                <path
                  d="M21 3L11 10L1 3"
                  stroke="#141212"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <a href="mailto:info@ascendo.do">info@ascendo.do</a>
            </li>
          </ul>
        </address>
      </div>
      <div class="section">
        <div class="subsection">
          <h3>Dirección</h3>
          <address class="details">
            <p>
              Amelica Francasci #12, Los Prados, Santo Domingo, República
              Dominicana
            </p>
            <a
              target="_blank"
              rel="noreferrer noopener"
              href="https://goo.gl/maps/CFgjvawdDor2wX9G6"
              class="maps"
              ><svg
                class="map-svg"
                viewBox="0 0 20 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M19 10C19 17 10 23 10 23C10 23 1 17 1 10C1 7.61305 1.94821 5.32387 3.63604 3.63604C5.32387 1.94821 7.61305 1 10 1C12.3869 1 14.6761 1.94821 16.364 3.63604C18.0518 5.32387 19 7.61305 19 10Z"
                  stroke="#141212"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
                <path
                  d="M10 13C11.6569 13 13 11.6569 13 10C13 8.34315 11.6569 7 10 7C8.34315 7 7 8.34315 7 10C7 11.6569 8.34315 13 10 13Z"
                  stroke="#141212"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <span>Ver en Google Maps</span></a
            >
          </address>
        </div>
        <div class="subsection">
          <h3>Horario</h3>
          <address class="details">L-V: 8:30 a.m. – 5:30 p.m.</address>
        </div>
      </div>
    </div>
  </footer>
</template>

<style lang="scss">
footer {
  padding: vwS(40) vwS(20);

  h2 {
    font-weight: 500;
    font-size: vwS(20);
    line-height: vwS(22);
    letter-spacing: 0.02em;
    text-transform: uppercase;
  }

  h3 {
    font-weight: 500;
    font-size: vwS(16);
    line-height: vwS(18);
    letter-spacing: 0.02em;
    text-transform: uppercase;
  }

  .information {
    margin-top: vwS(25);
    .section + .section {
      margin-top: vwS(25);
      margin-left: 0;
    }
  }

  .details {
    font-style: normal;
    font-size: vwS(16);
    line-height: vwS(20);
    letter-spacing: 0.02em;
    margin-top: vwS(10);

    ul {
      padding: 0;
    }

    .footer-link {
      display: flex;
      align-items: center;
      list-style: none;
      font-size: vwS(16);
      line-height: vwS(30);
      letter-spacing: 0.02em;
      text-transform: uppercase;
    }

    .footer-link a {
      text-decoration: none;
      color: #141212;
      margin-left: vwS(15);
      text-transform: uppercase;
    }

    .maps {
      margin-top: vwS(20);
      display: flex;
      text-decoration: none;
      color: #141212;
      align-items: center;

      span {
        margin-left: vwS(10);
      }
    }
  }

  .subsection + .subsection {
    margin-top: vwS(30);
  }

  svg.phone-svg {
    width: vwS(18);
    height: vwS(18);
  }

  svg.whatsapp-svg {
    width: vwS(18);
    height: vwS(18);
  }

  svg.email-svg {
    width: vwS(20);
    height: vwS(16);
  }

  svg.map-svg {
    width: vwS(18);
    height: vwS(20);
  }

  @include above(small) {
    padding: vw(70) vw(40) vw(40);
    display: flex;
    justify-content: space-between;

    h2 {
      font-size: vw(24);
      line-height: vw(26);
    }

    h3 {
      font-size: vw(18);
      line-height: vw(20);
    }

    .information {
      display: flex;
      margin-top: 0;
      padding-right: vw(40);

      .section + .section {
        margin-top: 0;
        margin-left: vw(100);
      }
    }

    .details {
      font-size: vw(18);
      line-height: vw(24);
      margin-top: vw(20);
      max-width: vw(300);

      .footer-link {
        font-size: vw(18);
        line-height: vw(35);
      }

      .footer-link a {
        margin-left: vw(15);
      }

      .maps {
        margin-top: vw(20);

        span {
          margin-left: vw(10);
        }
      }
    }

    .subsection + .subsection {
      margin-top: vw(40);
    }

    svg.phone-svg {
      width: vw(22);
      height: vw(22);
    }

    svg.whatsapp-svg {
      width: vw(20);
      height: vw(20);
    }

    svg.email-svg {
      width: vw(22);
      height: vw(18);
    }

    svg.map-svg {
      width: vw(20);
      height: vw(24);
    }
  }
}
</style>

// src/lib/components/Footer.svelte
<footer>
	<h2>ASCENDO</h2>
	<div class="information">
		<div class="section">
			<h3>Información de Contacto</h3>
			<address class="details">
				<ul>
					<li class="footer-link">
						<svg
							class="phone-svg"
							viewBox="0 0 22 22"
							fill="none"
							xmlns="http://www.w3.org/2000/svg"
						>
							<path
								d="M20.8881 15.9201V18.9201C20.8892 19.1986 20.8322 19.4743 20.7206 19.7294C20.6091 19.9846 20.4454 20.2137 20.2402 20.402C20.035 20.5902 19.7927 20.7336 19.5289 20.8228C19.265 20.912 18.9855 20.9452 18.7081 20.9201C15.631 20.5857 12.6751 19.5342 10.0781 17.8501C7.66194 16.3148 5.61345 14.2663 4.07812 11.8501C2.38809 9.2413 1.33636 6.27109 1.00812 3.1801C0.983127 2.90356 1.01599 2.62486 1.10462 2.36172C1.19324 2.09859 1.33569 1.85679 1.52288 1.65172C1.71008 1.44665 1.93792 1.28281 2.19191 1.17062C2.44589 1.05843 2.72046 1.00036 2.99812 1.0001H5.99812C6.48342 0.995321 6.95391 1.16718 7.32188 1.48363C7.68985 1.80008 7.93019 2.23954 7.99812 2.7201C8.12474 3.68016 8.35957 4.62282 8.69812 5.5301C8.83266 5.88802 8.86178 6.27701 8.78202 6.65098C8.70227 7.02494 8.51698 7.36821 8.24812 7.6401L6.97812 8.9101C8.40167 11.4136 10.4746 13.4865 12.9781 14.9101L14.2481 13.6401C14.52 13.3712 14.8633 13.1859 15.2372 13.1062C15.6112 13.0264 16.0002 13.0556 16.3581 13.1901C17.2654 13.5286 18.2081 13.7635 19.1681 13.8901C19.6539 13.9586 20.0975 14.2033 20.4146 14.5776C20.7318 14.9519 20.9003 15.4297 20.8881 15.9201Z"
								stroke="#141212"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							/>
						</svg>
						<a href="tel:+18092271112">+1 (809) 227-1112</a>
					</li>
					<li class="footer-link">
						<svg
							class="email-svg"
							viewBox="0 0 22 18"
							fill="none"
							xmlns="http://www.w3.org/2000/svg"
						>
							<path
								d="M3 1H19C20.1 1 21 1.9 21 3V15C21 16.1 20.1 17 19 17H3C1.9 17 1 16.1 1 15V3C1 1.9 1.9 1 3 1Z"
								stroke="#141212"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							/>
							<path
								d="M21 3L11 10L1 3"
								stroke="#141212"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							/>
						</svg>
						<a href="mailto:info@ascendo.do">info@ascendo.do</a>
					</li>
				</ul>
			</address>
		</div>
		<div class="section">
			<div class="subsection">
				<h3>Dirección</h3>
				<address class="details">
					<p>Amelica Francasci #12, Los Prados, Santo Domingo, República Dominicana</p>
					<a
						target="_blank"
						rel="noreferrer noopener"
						href="https://goo.gl/maps/CFgjvawdDor2wX9G6"
						class="maps"
					>
						<svg class="map-svg" viewBox="0 0 20 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path
								d="M19 10C19 17 10 23 10 23C10 23 1 17 1 10C1 7.61305 1.94821 5.32387 3.63604 3.63604C5.32387 1.94821 7.61305 1 10 1C12.3869 1 14.6761 1.94821 16.364 3.63604C18.0518 5.32387 19 7.61305 19 10Z"
								stroke="#141212"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							/>
							<path
								d="M10 13C11.6569 13 13 11.6569 13 10C13 8.34315 11.6569 7 10 7C8.34315 7 7 8.34315 7 10C7 11.6569 8.34315 13 10 13Z"
								stroke="#141212"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							/>
						</svg>
						<span>Ver en Google Maps</span>
					</a>
				</address>
			</div>
			<div class="subsection">
				<h3>Horario</h3>
				<address class="details">L-V: 8:30 a.m. – 5:30 p.m.</address>
			</div>
		</div>
	</div>
</footer>

<style>
	footer {
		padding: calc(40 / 375 * 100vw) calc(20 / 375 * 100vw);

		h2 {
			font-weight: 500;
			font-size: calc(20 / 375 * 100vw);
			line-height: calc(22 / 375 * 100vw);
			letter-spacing: 0.02em;
			text-transform: uppercase;
		}

		h3 {
			font-weight: 500;
			font-size: calc(16 / 375 * 100vw);
			line-height: calc(18 / 375 * 100vw);
			letter-spacing: 0.02em;
			text-transform: uppercase;
		}

		.information {
			margin-top: calc(25 / 375 * 100vw);

			.section + .section {
				margin-top: calc(25 / 375 * 100vw);
				margin-left: 0;
			}
		}

		.details {
			font-style: normal;
			font-size: calc(16 / 375 * 100vw);
			line-height: calc(20 / 375 * 100vw);
			letter-spacing: 0.02em;
			margin-top: calc(10 / 375 * 100vw);

			ul {
				padding: 0;
			}

			.footer-link {
				display: flex;
				align-items: center;
				list-style: none;
				font-size: calc(16 / 375 * 100vw);
				line-height: calc(30 / 375 * 100vw);
				letter-spacing: 0.02em;
				text-transform: uppercase;
			}

			.footer-link a {
				text-decoration: none;
				color: #141212;
				margin-left: calc(15 / 375 * 100vw);
				text-transform: uppercase;
			}

			.maps {
				margin-top: calc(20 / 375 * 100vw);
				display: flex;
				text-decoration: none;
				color: #141212;
				align-items: center;

				span {
					margin-left: calc(10 / 375 * 100vw);
				}
			}
		}

		.subsection + .subsection {
			margin-top: calc(30 / 375 * 100vw);
		}

		:global(svg.phone-svg) {
			width: calc(18 / 375 * 100vw);
			height: calc(18 / 375 * 100vw);
		}

		:global(svg.email-svg) {
			width: calc(20 / 375 * 100vw);
			height: calc(16 / 375 * 100vw);
		}

		:global(svg.map-svg) {
			width: calc(18 / 375 * 100vw);
			height: calc(20 / 375 * 100vw);
		}

		@media (min-width: 768px) {
			padding: calc(70 / 1440 * 100vw) calc(40 / 1440 * 100vw) calc(40 / 1440 * 100vw);
			display: flex;
			justify-content: space-between;

			h2 {
				font-size: calc(24 / 1440 * 100vw);
				line-height: calc(26 / 1440 * 100vw);
			}

			h3 {
				font-size: calc(18 / 1440 * 100vw);
				line-height: calc(20 / 1440 * 100vw);
			}

			.information {
				display: flex;
				margin-top: 0;
				padding-right: calc(40 / 1440 * 100vw);

				.section + .section {
					margin-top: 0;
					margin-left: calc(100 / 1440 * 100vw);
				}
			}

			.details {
				font-size: calc(18 / 1440 * 100vw);
				line-height: calc(24 / 1440 * 100vw);
				margin-top: calc(20 / 1440 * 100vw);
				max-width: calc(300 / 1440 * 100vw);

				.footer-link {
					font-size: calc(18 / 1440 * 100vw);
					line-height: calc(35 / 1440 * 100vw);
				}

				.footer-link a {
					margin-left: calc(15 / 1440 * 100vw);
				}

				.maps {
					margin-top: calc(20 / 1440 * 100vw);

					span {
						margin-left: calc(10 / 1440 * 100vw);
					}
				}
			}

			.subsection + .subsection {
				margin-top: calc(40 / 1440 * 100vw);
			}

			:global(svg.phone-svg) {
				width: calc(22 / 1440 * 100vw);
				height: calc(22 / 1440 * 100vw);
			}

			:global(svg.email-svg) {
				width: calc(22 / 1440 * 100vw);
				height: calc(18 / 1440 * 100vw);
			}

			:global(svg.map-svg) {
				width: calc(20 / 1440 * 100vw);
				height: calc(24 / 1440 * 100vw);
			}
		}
	}
</style>
